### ISSUE TITLE
Ela counters Montagne

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#102]
https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/ecuw4rm/?context=3

**Comment by ribrah77** [comment]
New here, trying to push changes, getting an error message 

`remote: Permission to BurkusCat/r6-operator-counters.git denied to ribrah77.
fatal: unable to access 'https://github.com/BurkusCat/r6-operator-counters.git/': The requested URL returned error: 403`

Any help?

**Comment by BurkusCat** [comment]
Hey, thank you for getting involved! I've added you as a contributor to the project. You should be able to create and push to branches on the project now.

FYI, when you aren't a contributor on a project, the process is:
- Fork the repo
- Create a new branch on that repo and push your changes to it
- Create a pull request on the original repo and after it is reviewed, the changes will be merged in

Now that you are a contributor, step 1 is different, you can create branches on this repo and assign issues to yourself.

Let me know if you have any questions!

**Comment by ribrah77** [comment]
Hey, thanks for the help, im still having the same issue, did you give me permissions to push or should i just work from a fork?
