### ISSUE TITLE
Twitch's drone can see Echo's drone when cloaked

### ISSUE THREAD

**Issue by katzecat1** [BurkusCat/r6-operator-counters#113]
I've shot Echo's drone many times while on my Twitch drone. The current text for Twitch minor countering Echo is "Twitch's Drone can shoot Echo's Drone but is unable to see it when it is cloaked." 

It should just be "Twitch's Drone can shoot Echo's Drone." and it should probably be a soft counter instead of minor, as it destroys Echo's drone for the rest of the round, which isn't a minor counter.

**Comment by BurkusCat** [comment]
Is Twitch's drone able to see Echo's drone when it is cloaked? (Twitch can easily see a cloaked Gu mine for example)

Probably should be a soft counter as I believe the drone is hidden on the roof.

**Comment by abuDarda97** [comment]
Hi guys,

I am new to coding, I saw your issues on the "Up For Grabs" website. I have made changes on the r6OperatorsCounter.json file (added twitch's soft counter) on my local branch.  However, I don't have permission to push my branch, can I have access please?

Thanks,

Abu

**Comment by CrayCrayDecay** [comment]
Hi Abu,

Thanks for the submission. For the time being, you will have to fork
master, create a new branch, then create a pull request for that branch.

Thanks,
Alex

**Comment by JakeAMarq** [comment]
This can be closed now after #171!
