### ISSUE TITLE
Year 4 Season 2 Operators - Nøkk & Warden

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#122]
* Add new icons from https://marcopixel.eu/r6-operatoricons/
* Add operators to the graph
* Add any counter relationships for these operators
* Open a new issue for further relationship refinement after the operators have been released for a few days

Nøkk hard counters: Valk, Maestro
Nøkk soft counters: Echo, Mozzie
Mozzie soft counters: Nøkk
Echo soft counters: Nøkk

Warden hard counters: Ying
IQ hard counters: Warden
Thatcher hard counters: Warden

**Comment by marcopixel** [comment]
@BurkusCat Icons are done and should be ready to download 👍

**Comment by BurkusCat** [comment]
Cheers @marcopixel ! They look awesome 😍
