### ISSUE TITLE
Vigil counters Lion

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#135]
**Does this counter exist on the graph currently?**
~~Yes~~/No

**Counter information**
- Operator doing the countering: Vigil
- Operator being countered: Lion
- Counter level: [Hard Counter/~~Soft Counter/Minor Counter~~]
- Description of how one operator counters the other operator: Vigil cannot be detected by Lion's EE-ONE-D drone scan when his ER7-C gadget is active,

**Do you think the community would agree with this information?**
Yes

**Comment by tsangjustin** [comment]
Can this ticket be closed? Seems like a PR that resolves this counter is merged

**Comment by CrayCrayDecay** [comment]
If this issue was resolved in a previous commit, please feel free to close
it.
