### ISSUE TITLE
Year 5 Season 1 Operators - Oryx and Iana

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#152]
- Add new icons from https://marcopixel.eu/r6-operatoricons/
- Add operators to the graph
- Add any counter relationships for these operators
- Open a new issue for further relationship refinement after the operators have been released for a few days

### Some thoughts on potential counters:
Oryx counters:
- Montagne, Blitz

Oryx is countered by:
- Nomad

Iana is countered by:
- Mute
- Maestro (hologram doesn't show up on thermal)
- Vigil can't be seen by Iana. Can she still see the "nearby" effects like a drone can?

**Comment by marcopixel** [comment]
@BurkusCat I've made an NPM package which should help you with a cleaner integration + add additional metadata (like op role, unit, etc..) for your project.

https://github.com/marcopixel/r6operators

Feel free to contact me if there's anything missing you might need or if you need some help with it :)

**Comment by BurkusCat** [comment]
That is excellent! I will try integrate this and see how it goes :)
