### ISSUE TITLE
Switch to using .pngs

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#156]
**Is your feature request related to a problem? Please describe.**
The site performs quite badly.

**Describe the solution you'd like**
By default, use .PNG files. They perform a lot better despite being larger.

Give an option to switch to a "High detail graphics (slow)" mode from "Medium detail graphics (fast)".

**Comment by Mr-Martinez** [comment]
I'm curious, could issue #111  link tie in with .png files? I did a quick read and saw that a mixture of 'd3' graph making along with html drawing can help speed things up. I'm thinking, would it speed up if we could use png's in favor of svg files in addition to using html drawing?

**Comment by BurkusCat** [comment]
These tickets are definitely related, but I wouldn't combine. I think both things would help improve performance. However, #111 I imagine would be a lot bigger change. So I'm only going to look at the .png changes for now.
