### ISSUE TITLE
Mobile Version

### ISSUE THREAD

**Issue by Mr-Martinez** [BurkusCat/r6-operator-counters#166]
**Issue**
Looking through the website in mobile is an issue. Maybe a redesign of how data is displayed to users

**Describe the solution you'd like**
Maybe a layout change to mobile to look like this:
https://rankedboost.com/league-of-legends/counter/lee-sin/

With explanations such as this:
https://lolcounter.com/champions/zed

Basically just showing data to the phone.

**Comment by BurkusCat** [comment]
Most things do work quite well on mobile. I think some UI enhancements like this one will declutter things #117 (I'm planning to look into this one soon).

Is there anything in particular you think is an issue on mobile? I like the look of the site you linked but personally, I would make it an optional view or maybe even link to a page like that from the homepage of the site.

**Comment by Mr-Martinez** [comment]
No, it works. 
On my iPhone X, I can move, zoom in/out. 
One thing I can't do well is seeing the "big picture." I have to follow the lines to each operator.

An optional view or a link to a page is a good idea.

**Comment by Mr-Martinez** [comment]
I will close this issue in favor of #117.
This is well detailed issue that includes UI enhancements with regards to screen sizes.
