### ISSUE TITLE
Adding minor counters for Buck against Anti-Breach operators and Anchors

### ISSUE THREAD

**Issue by AarnavSan** [BurkusCat/r6-operator-counters#231]
**Does this counter exist on the graph currently?**
Yes

**Counter information**
-Buck
- Anti-Breach operators like Bandit/Kaid and Anchors like Tachanka
- Minor Counters
- Buck uses vertical play to counter Anti-Breach operator gadgets as well as clearing out angles that an anchor like Tachanka can hole up and play in

**Do you think the community would agree with this information?**
Buck is the only operator with 0 counters on the graph so adding some minor counters would help visualize Buck's usability in the game

**Comment by yonichanowitz** [comment]
made a PR. https://github.com/BurkusCat/r6-operator-counters/pull/237

i didn't include the Tchanka counter mentioned in the comment above, as the same logic can reasonably apply to all 1 speed operators

**Comment by mzrokz** [comment]
I can see that the PR is merged. Just trying to understand why this issue is not closed. Also is this repo still active, I was thinking to contribute but not sure if members are still active.

**Comment by BurkusCat** [comment]
Hey @mzrokz, I haven't made changes to this repo in a good while but I still review PRs if you are interested in contributing :)

Thanks for pointing out this issue should have been closed!
