### ISSUE TITLE
Upgrade to ES6

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#39]
- Running gulp fails when using ES6 code
- Take advantage of some ES6 features to test out it is allowed

**Comment by BurkusCat** [comment]
https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/

**Comment by schang1146** [comment]
So... apparently a lot of the examples for #67 require ES6 code... So I'll be trying to upgrade to ES6... RIP

**Comment by schang1146** [comment]
This can be closed now?

**Comment by BurkusCat** [comment]
Closed
