### ISSUE TITLE
Should "Minor counters" be renamed?

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#4]
- "Hard counters" and "Soft counters" are well established gaming terms.
- However, "Soft counter" is a bit too strong of a term to describe some of the cool little interactions in this game.
- For example, an operator that dies can drop their phone into electrified barbed wire and have it destroyed. This denies Dokkaebi a phone to pick up. A super small gameplay interaction but still nice to note.

**Comment by Raddish18** [comment]
Minor or Trivial sound good to me

**Comment by BurkusCat** [comment]
Staying as Minor
