### ISSUE TITLE
Ash & Zofia counters Maestro

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#55]
https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/ectclof/?context=3

https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/ectitpu/?context=3

**Comment by BurkusCat** [comment]
Torn on whether to include Buck with his grenades or not.

**Comment by Archeol** [comment]
Nah, leave the grenades out, in that case might as well add breach charges. maybe as a trivia category?. But his shotgun should drop/breaks the cam when shot _around_ it/breaks the wall.
