### ISSUE TITLE
Jackal counters Cav

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#56]
https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/ectd8fa/?context=3

Maybe a minor counter considering that if he does spot her footsteps, it shuts down her roaming.

**Comment by ihasmagyk** [comment]
They should probably counter each other, since it’s almost a game of luck whether or not Jackal is able to scan Cav

**Comment by Trufflegator** [comment]
Should this be resolved(Invis footsteps > tracking)? Or would pursuing this:

> They should probably counter each other, since it’s almost a game of luck whether or not Jackal is able to scan Cav

be worthwhile?

**Comment by BurkusCat** [comment]
I think lets mark it as resolved. Her ability directly counters his. There are lots of characters used as roamers in this game but it would probably clutter the graph too much to have them all listed as being countered by Jackal.
