### ISSUE TITLE
Clash/Ela counters Montagne

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#63]
https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/ecthsgw/?context=3

https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/ectt1ns/?context=3

**Comment by AustinGallippo** [comment]
Hey, can I work on this?

**Comment by BurkusCat** [comment]
Yes that would be great! 😀

**Comment by AustinGallippo** [comment]
It already looks like it should should the correct counter for Ela and Montange unless I'm wrong.
