### ISSUE TITLE
Double click an operator to focus the graph on them

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#67]
https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/ectliik/?context=3

- Need to think carefully about how to unfocus from an operator to view the whole graph again
- Make irrelevant relationships/operators translucent or darker?
- Need to experiment with:
    - Double click to focus on a relationship/operator?
    - Hover to focus on a relationship/operator (tap on mobile)?
    - Tap/single click to focus on a relationship/operator?

**Comment by BurkusCat** [comment]
https://bl.ocks.org/almsuarez/4333a12d2531d6c1f6f22b74f2c57102

**Comment by BurkusCat** [comment]
@J-888 made a really good concept for how it should look: https://imgur.com/fDzguF0

**Comment by schang1146** [comment]
Heyo, gonna give this a shot. Wish me luck.

**Comment by BurkusCat** [comment]
Sounds good, best of luck @schang1146 :)

**Comment by BurkusCat** [comment]
Hey @schang1146, are you still interested on working on this issue at some stage? 😊

There is absolutely no pressure to say yes or no btw. Just thought I'd check in! :)

**Comment by schang1146** [comment]
Have to say probably not at the moment, busy with some stuff and won't have the chance to work on it. Sorry!
