### ISSUE TITLE
Option to disable physics and show a static grid

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#69]
https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/ectlryd/?context=3

- Start/restart simulation?
- Need to allow drag events still
- What about a toggle button to "stick all operators" and "unstick all operators"
    - sticking currently happens when you drag an operator

**Comment by APupper** [comment]
Yes please
