### ISSUE TITLE
Do Bandit/Kaid counter Maverick?

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#76]
https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/ectmtst/?context=3

**Comment by Archeol** [comment]
Not really, perhaps as a minor counter since its not a big deal to take a step back and use the blowtorch from there to then destroy them

**Comment by orangeandblack5** [comment]
I would say that Maverick counters Bandit and soft-counters Kaid, but Kaid minor counters Maverick, as the electroclaws, unlike Bandit's batteries, can be placed in any location on the reinforced panel, and thus Maverick can not destroy them as reliably.

**Comment by Trufflegator** [comment]
The Soft Counters for both are implemented, should they be ammended?

**Comment by BurkusCat** [comment]
Closing as they are implemented
