### ISSUE TITLE
IQ counters Kaid

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#93]
https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/

**Comment by kg609** [comment]
Hey There,

I'm new and would like to contribute to this project if possible. I would like to tackle this issue if it has not been claimed yet. Also would this be considered a hard or minor counter between these two ops? Thanks.

**Comment by Trufflegator** [comment]
Solved on 20 Oct 2019.
