### ISSUE TITLE
Dokkaebi counters Cav

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#94]
https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/ecu8irq/?context=3

**Comment by schang1146** [comment]
Title should be the other way around, Dokkaebi counters Caveira

**Comment by BurkusCat** [comment]
Feel free :)

Updated the title.

**Comment by Trufflegator** [comment]
Solved on 22 Oct 2019.
