### ISSUE TITLE
Thatcher counters Clash

### ISSUE THREAD

**Issue by BurkusCat** [BurkusCat/r6-operator-counters#96]
https://www.reddit.com/r/Rainbow6/comments/aam9o2/this_is_a_site_i_made_showing_how_different/ecuauop/?context=3

**Comment by schang1146** [comment]
Looks like this should be closed.
![image](https://user-images.githubusercontent.com/20074034/67166474-9be03a80-f344-11e9-9a63-38ad02868e3a.png)

**Comment by BurkusCat** [comment]
Yep, good spot!
